name = "dictionary"
version = "1.0.0"
migrations_dir = "./priv/migrations"
schemafile = "./schema.sql"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
wisp = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
mist = ">= 3.0.0 and < 4.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
lustre = ">= 4.6.3 and < 5.0.0"
cake = ">= 2.1.0 and < 3.0.0"
cake_sqlight = ">= 1.0.2 and < 2.0.0"
feather = ">= 1.2.0 and < 2.0.0"
clip = ">= 1.0.0 and < 2.0.0"
sqlight = ">= 0.9.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
glailglind = ">= 1.1.3 and < 2.0.0"

[tailwind]
args = [
    "--config=tailwind.config.js",
    "--input=./src/css/app.css",
    "--output=./priv/static/app.css",
]
